return {
	require("lazy.plugins.code.ansible"),
	require("lazy.plugins.code.autocompletion"),
	require("lazy.plugins.code.autopairs"),
	require("lazy.plugins.code.conform"),
	require("lazy.plugins.code.coverage"),
	require("lazy.plugins.code.dap"),
	require("lazy.plugins.code.git"),
	require("lazy.plugins.code.go"),
	require("lazy.plugins.code.lsp"),
	require("lazy.plugins.code.lua"),
	require("lazy.plugins.code.markdown"),
	require("lazy.plugins.code.neotest"),
	require("lazy.plugins.code.nvim-lint"),
	require("lazy.plugins.code.python"),
	require("lazy.plugins.code.treesitter"),
	require("lazy.plugins.code.yaml"),
}
